### ISSUE TITLE
Any one explain this code what exactly its doing ?

### ISSUE THREAD

**Issue by Rahulvks** [aneesha/RAKE#17]
i understand keyword extraction.Kindly explain how it is done using RAKE ?

**Comment by aneesha** [comment]
The algorithm is described in Rose S, Engel D, Cramer N, and Cowley, W. Automatic Keyword Extraction from Individual Documents, In: Berry MW, Kogan J, editors. Text Mining: Applications and Theory. Chichester, UK: John Wiley & Sons; 2010. doi: 10.1002/9780470689646.ch1
